---
name: Philippe
surname: Mongeon
position: "Assistant Professor"
address: "School of Information Management, Dalhousie University"
phone: 
www: pmongeon.github.io
email: "PMongeon@dal.ca"
twitter: philippemongeon
github: pmongeon
linkedin: philippe-mongeon
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# If you are looking for my courses:

-   Data Management/Database Management Systems
-   Introduction to Data Science
-   Information in Society
-   Bibliometrics and Scholarly Communications

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Ph.D. Information Science", "2018", "Université de Montréal", "Montréal, Canada",
  "Master of Informaton Science", "2013", "Université de Montréal", "Montréal, Canada"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Courses

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
