project:
  type: website
  output-dir: docs

website:
  title: "Philippe Mongeon"
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching
      - href: talks.qmd
        text: Talks
      - href: publications.qmd
        text: Publications
      - href: blog.qmd
        text: Blog
format:
  html:
    toc: true
    code-link: false
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
    css: styles.css
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">


editor: visual

