---
title: "Measuring Engagement with Marine Environmental Science Grey Literature: A Case Study of GESAMP"
subtitle: (Article)
date: 2025-07-03
author: 
  - Rémi Toupin
  - Madelaine Hare
  - Kellie Dalton
  - Geoff Krause
  - Valeriia Moroz
  - Philippe Mongeon
authors:
  - name: Rémi Toupin
    orcid: 0000-0001-6765-0380
    corresponding: true
    email: remi.toupin@dal.ca
    affiliations: 
      - ref: dal
  - name: Madelaine Hare
    orcid: 0000-0002-2123-9518
    corresponding: false
    affiliations: 
      - ref: dal
  - name: Kellie Dalton
    orcid: 0009-0008-3692-2505
    corresponding: false
    affiliations: 
      - ref: dal
  - name: Geoff Krause
    orcid: 0000-0001-7943-5119
    corresponding: false
    affiliations:
      - ref: dal
  - name: Valeriia Moroz
    orcid: 0009-0004-1110-9404
    corresponding: false
    affiliations: 
      - ref: dal
  - name: Philippe Mongeon
    orcid: 0000-0003-1021-059X
    corresponding: false
    affiliations: 
      - ref: dal
affiliations:
  - id: dal
    name: Dalhousie University
    address: Halifax, Nova Scotia, Canada
  - id: cfa
    name: Aarhus University
    address: Aarhus, Denmark
categories: 
  - Science-policy interface
  - Knowledge mobilization
  - Altmetrics
bibliography: files/references.bib
csl: files/apa.csl
# doi: https://doi.org/10.1162/qss.a.5

code-overflow: wrap
code-tools: 
  source: FALSE
  toggle: TRUE
execute:
  warning: false
  message: false
  error: false
  echo: false
editor_options: 
  chunk_output_type: inline
  
draft: true
---

# Abstract

Environmental scientific advisory organizations and expert groups play a crucial role in synthesizing and disseminating knowledge to various stakeholders to inform practice and policy. This work is commonly disseminated through grey literature (e.g., reports and policy briefs). However, assessing the visibility, use, or impact of these outputs can be challenging because they often lack standard identifiers, such as DOIs, and are therefore not indexed in citation indexes and other databases commonly used to measure engagement using indicators like the number of views, downloads, or citations. Using the reports produced by the Joint Group of Experts on the Scientific Aspects of Marine Environmental Protection (GESAMP) as a case study, this study explores the use of various data sources (Web of Science, Overton and news indexing platforms) to track references to GESAMP reports in the scholarly literature, policy documents, and news media. Our findings indicate that attention to GESAMP reports has increased over the past twenty years, particularly in the last decade. GESAMP reports appear to generate interest in research fields dealing with environmental pollution and ocean management. Outside of academia, while sponsoring organizations tend to cite GESAMP the most, the reports also attract the interest of national and regional environmental organizations. Our study provides empirical evidence on how such reports and the organizations producing them can reach different audiences.

# Introduction

The production and dissemination of scientific knowledge constitute a critical foundation for the development of evidence-based policy frameworks and coordinated societal responses to pressing socioenvironmental challenges. In the context of accelerating climate change, ecological degradation, and widening social inequities, integrating robust empirical research into decision-making processes is essential for ensuring that interventions are both effective and equitable. Scientific inquiry not only elucidates the underlying drivers and systemic interdependencies of environmental phenomena but also enables the modelling of future scenarios and the evaluation of policy outcomes across temporal and spatial scales [@canada2020climatescience]. The dissemination and engagement with scientific knowledge facilitate its translation into action [@tangney2022]. There is an imperative to produce knowledge that responds to policy priorities. As such, the strategic creation and circulation of scientific knowledge must be recognized as a cornerstone of informed governance and collaborative action in the Anthropocene [@morgan2018].

International scientific advisory bodies, such as the United Nations’ (UN) Joint Group of Experts on the Scientific Aspects of Marine Environmental Protection (GESAMP), bridge the scientific and public spheres by conducting research, synthesizing knowledge, and formulating recommendations for policymakers on key issues, including marine pollution and ocean acidification. Established in 1969, GESAMP functions under the auspices of ten UN organizations with overlapping maritime and ocean interests. Studies and assessments are conducted by dedicated Working Groups, comprised of a multidisciplinary group of experts on the subject matters of specific projects to provide insights alongside advice for science-led solutions. 

GESAMP primarily contributes knowledge about ocean sustainability issues to the scientific community and worldwide marine protection advisory bodies through knowledge reports and thematic documents. GESAMP has produced over 120 sessional and topical reports, ranging from specific issues relating to marine protection—such as their 1985 study Atmospheric Transport of Contaminants into the Mediterranean Region—to higher-level publications that survey the current state of our oceans, such as A Sea of Troubles: Issues in Focus (2001), and more recent assessments like Marine Biofouling: Non-Indigenous Species and Management Across Sectors (2024), which explores the ecological and regulatory challenges posed by biofouling and its role in the spread of invasive species.

GESAMP’s research has been characterized as ranging “from in-depth reviews of critical marine processes, perturbations and contaminant categories to advice on monitoring, assessment and modelling, and guidance on strategic aspects of marine environmental protection and management” [@wells2002caring, p.80]. Indeed, GESAMP is unique in that it is made up of individuals from autonomous organizations, ultimately legitimizing its activities and research credibility for the international community as it operates “at arm’s length from a government, although in this case, the government is not one body but is itself a network of officials drawn from eight \[now ten\] governing bodies” [@mclaren1990network, p.657].

Studies on communicating knowledge to decision-making bodies [@cossarini2014communicating] , stakeholders [@soomai2013communicating], and informing policies [@lawrence2014evidence] provide context for understanding how information relating to coastal and marine protection produced by expert advisory groups is translated into the public sphere, used to shape environmental management decisions at all levels, and communicated to stakeholders who can be informed by the knowledge produced by these groups.  

Thus, contemporary scientific research and policymaking have built upon knowledge produced by GESAMP over the decades [@watsonwright2024gesamp]. Twenty years ago, studies by @cordes2003grey and @macdonald2004grey specifically aimed to capture the engagement with and use of GESAMP reports in the scholarly and policy literature. Our study serves as a follow-up to this work, incorporating recent reports and integrating new indicators, such as mentions of the reports in policy documents and news media.

## Challenges in measuring the use and impact of grey literature

Grey literature is a term used to encompass a wide range of documents produced all levels and sectors of government, academia, industry, or other [@schopfel2011prague]. Grey literature does not usually go through the scientific peer review process, and it can thus be published and disseminated quickly and communicate complex information to non-specialist audiences in an accessible format [@pappas2011grey].

For these reasons, its inclusion in systematic reviews and use in policymaking has risen over the past few decades [@pappas2011grey; @lawrence2014evidence; @macdonald2016science; @thatje2007elNino; @babarczy_national_2024; @paez2017; @adams2017]. However, its lack of indexing in citation databases makes assessing its use and impact difficult, which is important for encouraging successful types of grey literature and recognizing their contributions to knowledge advancement [@bickley2020impact]. @wilkinson2014substance proposed a web impact report indicator to identify web pages that cite or mention the documents in question, to be used in conjunction with other altmetric indicators (e.g., newspaper mentions). While such an indicator might account for use, the authors note that its limitations endure in assessing impact. It remains a managerial decision to gauge whether such indicator results are significant [@wilkinson2014substance]. @bickley2020impact used a semi-automated method, using Scopus (API) cited reference searches to locate grey literature citations and the Google Books API to identify monograph citations. They advanced a new approach in 2022 by using Publish or Perish and Webometric Analyst software and found it possible to match references in grey literature to academic publications (Bickley et al., 2022). @saleem2023referencing investigated evidence produced and relied on by non-academic organizations in the policy sphere and found an increasing reliance on grey literature. 

Attempts have been made to assess the use and impact of GESAMP-specific literature [@cordes2003grey; @macdonald2004grey; @hutton2009scientific]. @cordes2003grey conducted a citation analysis using the Web of Science, and MacDonald et al. (2004) employed a similar approach to assess the use of GESAMP literature.

@hutton2009scientific utilized the Web of Science, Google, and Google Scholar to investigate the influence of grey literature, advocating for a multifaceted approach to understanding GESAMP's influence through diverse citation data and indicators. @adie2014grey similarly suggested that investigations of the use and impact of grey literature could be improved through the assignment of persistent identifiers, advanced metadata standards, and open, central indexes or repositories of grey literature.

Examining a range of altmetric indicators, in addition to citations, and utilizing new data sources, such as the Overton[^1] database (founded by Adie), provides a means of capturing the impact of grey literature within and beyond the scientific community.

[^1]: <https://www.overton.io/>

# Research Objectives

This study examines engagement with GESAMP reports in research, policy, and the news media. As scholarly citations, policy mentions, and news mentions may be associated with different forms of scientific and public contributions to knowledge and policy, they illuminate attention given toward the outputs of scientific organizations [@afinowi2025mapping; @alperin2024second; @haustein2016interpreting; @toupin2023shark]. This study investigates the presence of GESAMP’s research outputs in the scholarly and public spheres. It aims to answer the following research questions:

**RQ1.** What is the prevalence of GESAMP publications in the scholarly literature, policy documents, and the news?

**RQ2.** What are the characteristics of GESAMP's most cited and mentioned publications?

Since the reports produced by GESAMP have employed different formats and addressed various topics and issues over the years, engagement may be variable in research, policy, and news media, as well as being embedded in specific contexts of production and communication. Also significant to this study is an examination of the types of attention received by GESAMP publications. This study thus assesses GESAMP’s presence in the scholarly literature and public sphere as indicated by the number of citations, news mentions, and policy mentions of their reports.

# Methods

This study focuses on the analysis of GESAMP work as listed under the Publications page of the organization’s website. The GESAMP website’s Publications page lists annual reports, thematic reports, proceedings, executive summaries, and histories of GESAMP as part of its Reports and Studies series, without differentiating between these document types. Therefore, we use the term "publications" to refer to the totality of GESAMP work listed on its website. Specifically, we collected information about 120 publications published between 1969 and 2022. Two publications – Report of the 32nd Session of GESAMP (#73) and Guidance on Assessment of Sediment Quality (#4) – are unavailable digitally as of December 2024. Therefore, data about these reports were only partially collected for this study. We first created a database of GESAMP publications containing the fields listed in Table 1. For each report, we also recorded the contributors and people associated with it, as mentioned in the individual reports, as well as their affiliation (institution and country) when available and their role concerning a report and GESAMP, resulting in a dataset of 1,625 individuals, scaled to 950 distinct individuals after disambiguation of duplicates and different writing styles for the names.

```{r message=FALSE, warning=FALSE}
#| label: tbl-1 
#| tbl-cap: "Fields used to document GESAMP reports"
library(tidyverse)
library(flextable)

table1<-tibble(Field = c("ID",
                         "Title",
                         "Abstract",
                         "Publication year",
                         "Publication type",
                         "Series name",
                         "Publisher",
                         "Number of pages",
                         "Working group",
                         "URL",
                         "Suggested citation format"),
               Description = c("A unique identifier for the publication. When available, the publication number is the ID.",
                               "The title of the publication.",
                               "The abstract for the publication.",
                               "The year of publication.",
                               "The type of publication (annual report, thematic report, proceedings, executive summary, history [of GESAMP]).",
                               "The name of the Reports and Studies series as listed on the website.",
                               "The publishing sponsoring organization (IMO, FAO, UNESCO-IOC, UNIDO, WMO, WHO, IAEA, UN, UNEP, ISA, or UNDP).",
                               "Number of pages of the publication.",
                               "The working group associated with the publication if available.",
                               "The URL of the publication from the GESAMP website.",
                               "The suggested citation format as indicated in the publication."))

table1 %>% 
  flextable() %>% 
  set_table_properties(width = 1, layout = "autofit")
```


## Citations

Web of Science cited references data accessed through the Obersvatoire des sciences et des technologies (OST) at the Université du Québec à Montréal, we searched for the strings “gesamp” and “group of experts on the scientific aspects of marine” in three locations: 1) the cited reference author, 2) the cited reference title, and 3) the cited reference source. It is worth noting that the these fields of the Web of Science database contain minimally processed or cleaned data. For example, there were 399 text strings representing GESAMP as the cited reference author. Overall, we retrieved 3,489 distinct reference strings (distinct references in which GESAMP was mentioned) from a total of 4,713 references made by 4,082 distinct publications.

## Policy Citations

GESAMP thematic reports, annual reports, histories, proceedings, and executive summaries were searched in the Overton database to collect citations by policy documents. Overton is the largest searchable index of policy documents, guidelines, think tank publications and working papers. Overton relies on Crossref, OpenAlex, and Wikidata infrastructures to collect citations and mentions of these documents. The Overton database provides citation contexts by indicating where a scholarly output is used in the text of a policy document (when a bibliography section is provided in a policy document, it maps to its DOI) (Szomszor & Adie, 2023). As the referencing practices of grey literature can vary, Overton typically relies on a set of scored features to capture citations. If the overall score exceeds a certain threshold, the citation context is matched to Crossref to capture citations to scholarly literature or the rest of the Overton database for policy documents. Overton also provides data such as authors of policy documents, source type (e.g., government, think tank), document topics, associated Sustainable Development Goals and the name of the source organization that produced the policy document (e.g., UNESCO, Institute for European Environmental Policy, Government of Canada) as matched by their internal methods.

GESAMP literature was searched individually by title. A search for GESAMP was also run, supplementing missing titles indexed under different names. Most (118 out of 120) of GESAMP's outputs were found in Overton, resulting in 2,112 citations. After removing self-citations between GESAMP publications, we retrieved 742 references in 551 distinct publications by 103 organizations linking to GESAMP publications. Notably, many policy citations are self-references by the organization to its own literature. However, this may be due to an artefact in the data collection process as many of these citations referred to the list of GESAMP’s previous reports present at the end of each of its publications. 

For the analysis, we counted the number of citations per year, the number of citations per citing organization, and the number of citations to each report.

## News Mentions

News articles were collected from five databases: Factiva, Eurêka, ProQuest News and Newspapers, NexisUni, and Research Library, chosen for their international scope and the relevance of their available resources. 

The Factiva database indexes news from over 33,000 sources globally. Emphasizing business and market intelligence data, the available sources include newspapers, trade publications, government publications, and press releases. A search for “GESAMP” or “group of experts on the scientific aspect of marine” retrieved 401 results, exported as headline data in HTML and converted to Comma Separated Values (CSV) files with an R script and manual cleaning, resulting in a final CSV file of 346 exported results.

The Eurêka database indexes approximately 2,500 sources covering current events on the local, regional, national, and international levels. “GESAMP” or “group of experts on the scientific aspect of marine” was searched in all its archives and content. This search retrieved 213 results, which were exported in a Research Information Systems (RIS) file and thenconverted to CSV format.

The ProQuest News and Newspapers database includes seven newspapers/services: Canadian Newsstream, Global Breaking Newswires, International Newsstream, ProQuest Historical Newspapers: The Globe and Mail, ProQuest Historical Newspapers: The New York Times with Index, ProQuest Historical Newspapers: Toronto Star, and U.S. Newsstream. A search for “GESAMP” or “group of experts on the scientific aspect of marine” retrieved 93 results, which were exported as an XLSX file and converted to CSV format.

The NexisUni database indexes over 15,000 news, business, and legal source articles focusing on business, political science, and criminal justice. NexisUni provides many resources, including newspaper and newswire feeds. A search for “GESAMP” or “group of experts on the scientific aspects of marine" retrieved 189 results, which were compiled into a CSV file. 

The Research Library database searches multiple interdisciplinary journal sources spanning multiple disciplines and fields. With an international scope, the database comprises a smaller collection of sources, including over 2,300 journals and newspaper sources, as well as recent newswire feeds. A search for “GESAMP” or “group of experts on the scientific aspects of marine” produced 70 results compiled into a CSV file.

The combined news mentions dataset contains 911 items with seven metadata fields. After filtering out items with the type “journalArticle” from the Eurêka results (62 items), unique news items can be distinguished by title, publication, and year, leaving 716 results. Note that this curated dataset does not preclude duplicates published in multiple publications or translated works. The earliest news mention of GESAMP found in any database dates back to 1988. We subsequently examined the context in which GESAMP was mentioned to identify the specific report that was mentioned. The resulting dataset included 217 news items related to GESAMP publications. 

For the analysis, we counted the number of news mentions to GESAMP per year, the number of mentions per media source, and the number of news mentions to individual reports.

# Results

## Reports

We first examined the type of GESAMP publications through the years (Table 2). The number of thematic reports dipped slightly in the 2000-2009 decade, with no reports published between 2003 and 2007. There has, however, been an increase in thematic reports during the 2010-2022 period.

Table 2. Number of GESAMP publications by period and by type.

|                   |           |           |           |           |           |       |
|-----------|-----------|-----------|-----------|-----------|-----------|-----------|
| Publication type  | 1969-1979 | 1980-1989 | 1990-1999 | 2000-2009 | 2010-2022 | Total |
| Thematic Report   | 5         | 20        | 18        | 8         | 14        | 65    |
| Annual Report     | 10        | 9         | 10        | 7         | 12        | 48    |
| History           | 0         | 0         | 1         | 2         | 0         | 3     |
| Proceedings       | 0         | 0         | 0         | 0         | 3         | 3     |
| Executive Summary | 0         | 0         | 0         | 0         | 1         | 1     |
| Overall           | 15        | 29        | 29        | 17        | 29        | 120   |

We also identified the sponsoring organizations that acted as editors for the published work through the years (Table 3). The International Maritime Organization (IMO), where GESAMP’s main office is located, contributed the highest number of publications, especially in recent years, followed by the Food and Agriculture Organization of the United Nations (FAO) and the World Meteorological Organization (WMO). Notably, the participation of the FAO as an editor has been constant through the years.

Table 3. Number of GESAMP publications by period and by publisher.

|             |           |           |           |           |           |       |
|-------------|-----------|-----------|-----------|-----------|-----------|-------|
| Publisher\* | 1969-1979 | 1980-1989 | 1990-1999 | 2000-2009 | 2010-2022 | Total |
| IMO         | 0         | 1         | 7         | 4         | 13        | 25    |
| FAO         | 6         | 4         | 6         | 3         | 2         | 21    |
| WMO         | 1         | 6         | 4         | 1         | 4         | 16    |
| UNEP        | 0         | 3         | 4         | 3         | 4         | 14    |
| UNESCO      | 3         | 4         | 3         | 2         | 3         | 15    |
| UN          | 3         | 4         | 1         | 1         | 2         | 11    |
| IAEA        | 1         | 2         | 2         | 1         | 4         | 10    |
| WHO         | 1         | 4         | 2         | 0         | 0         | 7     |
| IMO         | 2         | 2         | 0         | 0         | 0         | 4     |
| UNDP        | 0         | 0         | 0         | 0         | 3         | 3     |
| UNIDO       | 0         | 0         | 0         | 1         | 2         | 3     |
| Overall     | 17        | 30        | 29        | 16        | 37        | 129   |

\*International Maritime Organization (IMO); Food and Agriculture Organization (FAO); World Meteorological Organization (WMO); United Nations Environment Programme (UNEP); United Nations Educational, Scientific and Cultural Organization (UNESCO); United Nations (UN); International Atomic Energy Agency (IAEA); World Health Organization (WHO); International Maritime Organization (IMO); United Nations Development Programme (UNDP); United Nations Industrial Development Organization (UNIDO).  

## Citations in Peer-Reviewed Research Publications

Figure 1 indicates a steady increase in scholarly citations to GESAMP publications over time. Citations slightly increased after 2000 but fluctuated consistently every few years, and 2016 marks the beginning of a sharp increase in citations. Citation counts after 2020 may not accurately represent the full reach of publications, as citations take three years to accumulate and plateau, on average. 

(Figure_1_GESAMP.pdf)

GESAMP publications have been cited in works published by 1,120 journals. Figure 2 presents the top 25 journals that have cited GESAMP publications the most, with Marine Pollution Bulletin as the journal in which GESAMP publications are the most cited, and by a substantial number. This journal cited GESAMP literature over twice as much as Science of the Total Environment, which has the second highest number of citations to GESAMP work. Environmental Pollution, Ocean & Coastal Management, and Frontiers in Marine Science, comprising the rest of the top 5 journals citing GESAMP publications, indicate a focus on pollution and ocean management. The topic of pollution is also present among the remaining top 20 journals (such as Environmental Science and Pollution Research, Bulletin of Environmental Contamination and Toxicology, and Water Air and Soil Pollution) as are the subjects of toxicology and hazardous materials (Chemosphere, Journal of Hazardous Materials, Ecotoxicology and Environmental Safety, and Aquatic Toxicology), indicating the relevance and utility of GESAMP literature to research published in these journals. Other journals tend to focus on science, technology, ecology, environmental/marine research and management, whereas topics relating to policy appear less represented, although several key marine management journals such as Marine Policy and Coastal Management show significant interest in GESAMP work. 

(Figure_2_GESAMP.pdf)

Publication-level references to GESAMP work show that the three most cited GESAMP reports deal with issues related to plastic pollution in marine environments (#90, #99, #93 – Table 4). Other works that attracted a substantial degree of attention by scholars include two keystone reports about marine pollution issues, The State of the Marine Environment (#39) and A Sea of Troubles (#70), as well as papers dealing with land-based contamination (#71, #32) and chemical/oil pollution (#50, #75, #65). Another report appearing in the most cited publications of GESAMP is The Revised GESAMP Hazard Evaluation Procedure for Chemical Substances Carried by Ships (#64), which provides guidelines for the transport of chemical substances in ships, updated in recent reports. While the three most cited reports were published in recent years, citations to recent GESAMP work still need some time to accumulate, as the other 12 publications included in the top 15 most cited reports were published more than 12 years ago.

Table 4. Publication-level citations to GESAMP reports

|  |  |  |
|------------------------|------------------------|------------------------|
| **Title** | **Year** | **Citations** |
| Sources, Fate and Effects of Microplastics in the Marine Environment (Part 1) (#90) | 2015 | 840 |
| Guidelines for the Monitoring and Assessment of Plastic Litter in the Ocean (#99) | 2019 | 436 |
| Sources, Fate and Effects of Microplastics in the Marine Environment (Part 2) (#93) | 2016 | 406 |
| The State of the Marine Environment (#39) | 1990 | 259 |
| The Contributions of Science to Integrated Coastal Management (#61) | 1996 | 160 |
| Protecting the Oceans from Land-based Activities (#71) | 2001 | 133 |
| Impact of Oil and Related Chemicals on the Marine Environment (#50) | 1993 | 132 |
| Land/Sea Boundary Flux of Contaminants: Contributions from Rivers (#32) | 1987 | 108 |
| Estimates of Oil Entering the Marine Environment from Sea-based Activities (#75) | 2007 | 97 |
| Opportunistic Settlers and the Problem of the Ctenophore Mnemiopsis leidyi Invasion in the Black Sea (#58) | 1997 | 96 |
| A Sea of Troubles (#70) | 2001 | 95 |
| The Atmospheric Input of Trace Species to the World Ocean (#38) | 1989 | 94 |
| Proceedings of the GESAMP Workshop on Microplastic particles (#82) | 2010 | 89 |
| Towards Safe and Effective Use of Chemical in Coastal Aquaculture (#65) | 1997 | 81 |
| The Revised GESAMP Hazard Evaluation Procedure for Chemical Substances Carried by Ships (#64) | 2002 | 78 |

## Policy citations

Figure 3 presents the number of policy citations to GESAMP publications. These are less frequent than citations in research or news mentions, but we observe a positive trend starting after 2000. 

(Figure_3_GESAMP.pdf)

Figure 4 shows the top 15 policy sources citing GESAMP literature in their indexed production. The United Nations Environment Programme and the Food and Agriculture Organization of the United Nations are the top two citers of GESAMP literature. Data collected from Overton reveals frequent self-citations of GESAMP to its own work; the top two citers corroborate the finding that the UN often draws on its own work to advance and build knowledge. Other top citers include the International Union for Conservation of Nature, the World Meteorological Organization, and UNESCO, which shows strong international confidence in GESAMP literature for their work. Other global bodies that are not solely mandated for environmental protection or have dedicated environmental units include the World Health Organization and the World Bank. Specific national or international actors include the State of South Australia (concerned mainly with protecting the Great Barrier Reef), Natural Resources Institute Finland, the German Institute for Economic Research, and the Publications Office of the European Union.

(Figure_4_GESAMP.pdf)

Table 5 shows the top 15 report-level policy citations to GESAMP Reports and Studies. Notably, 11 of the 15 publications were produced in the 2000s, despite GESAMP reports dating back to the 1960s. This indicates that GESAMP reports have informed policymaking in recent years, perhaps due to GESAMP establishing itself as an organization in its first few decades when grey literature was more difficult to source online. However, one report from the 1980s and three from the 1990s received significant engagement in policy documents: the 1980 report Interchange of Pollutants Between the Atmosphere and the Ocean, for example, received the third highest amount of policy mentions. The top two most cited reports are from more recent years and are complementary documents: Parts 1 (#90) and 2 (#93) of Sources, Fate and Effects of Microplastics in the Marine Environment appear to reflect important concerns in the policy sphere in recent years.

Table 5. Publication-level policy indicators to GESAMP reports

|  |  |  |
|------------------------|------------------------|------------------------|
| **Title** | **Year** | **Policy citations** |
| Sources, Fate and Effects of Microplastics in the Marine Environment (Part 1) (#90) | 2015 | 113 |
| Sources, Fate and Effects of Microplastics in the Marine Environment (Part 2) (#93) | 2016 | 81 |
| Interchange of Pollutants Between the Atmosphere and the Ocean (#13) | 1980 | 72 |
| Protecting the Oceans from Land-based Activities (#71) | 2001 | 45 |
| Planning and Management for Sustainable Coastal Aquaculture Development (#68) | 2001 | 34 |
| Guidelines for the Monitoring and Assessment of Plastic Litter in the Ocean (#99) | 2019 | 34 |
| The State of the Marine Environment (#39) | 1990 | 33 |
| Towards Safe and Effective Use of Chemical in Coastal Aquaculture (#65) | 1997 | 31 |
| Assessment and communication of environmental risks in coastal aquaculture (#76) | 2008 | 26 |
| A Sea of Troubles (#70) | 2001 | 24 |
| The Atmospheric Input of Chemicals to the Ocean (#84) | 2012 | 23 |
| Proceedings of the GESAMP Workshop on Microplastic particles (#82) | 2010 | 19 |
| The magnitude and impacts of anthropogenic atmospheric nitrogen inputs to the ocean (#97) | 2018 | 19 |
| Monitoring the Ecological Effects of Coastal Aquaculture Wastes (#57) | 1996 | 18 |
| Sea-based sources of marine litter (#108) | 2021 | 17 |

## News mentions

As Figures 1 and 3 showed an increase in citations in scholarly work and policy documents to GESAMP literature, Figure 5 also reveals a positive trend over the past two decades. After 2010 a noticeable rise in news mentions of GESAMP publications can be observed. In 2022 in particular there was a marked rise in news mentions, likely due to increased mainstream attention to the UN's declared Decade of Ocean Science for Sustainable Development (2021-2030) and the ongoing climate emergency (UNESCO, 2017; UNESCO-IOC, 2023).

(Figure_5_GESAMP.pdf)

These new works were published by 336 different publications/services, of which the top 25 are shown in Figure 6 below. Three of the top sources are American, indicating more attention from American news services to work produced by GESAMP. The top news sources are otherwise distributed across global news services, with representation from organizations such as All Africa, South China Morning post, and ForeignAffairs (New Zealand), as well as a large proportion of European news sources: Schiff und Hafen (Germany), La Repubblica (Italy), EUR-Lex, Twitter- Environnement (France), Lloyd's List (England), and European Union News. Overall, the representation of international news services is lesser than national sources. The World Bank (MENA Report) is also represented in the top news sources, as it is in top policy citers of GESAMP literature, the only organization other than the European Union to be represented in both policy and news groups. 

(Figure_6_GESAMP.pdf)

Report-level news mentions to GESAMP Reports and Studies are depicted in Table 6. Similar to Tables 4 and 5, reports #90 and #93 are among the top three reports mentioned in the news. News mentions seem more contemporary, with only two publications dating back to the 1990s and the rest published in the later 2010s. Table 6 also illustrates substantial overlap between news mentions and the two other groups of indicators: 7 of the top 15 reports are common to both policy and the news, while nine are common to citations and the news.

Table 6. Publication-level news indicators to GESAMP reports

|  |  |  |
|------------------------|------------------------|------------------------|
| **Title** | **Year** | **News mentions** |
| Sources, fate and effects of microplastics in the marine environment (Part 1) (#90) | 2015 | 39 |
| Sources, Fate and Effects of Microplastics in the Marine Environment (Part 2) (#93) | 2016 | 29 |
| A Sea of Troubles (#70) | 2001 | 15 |
| High Level Review of a Wide Range of Proposed Marine Geoengineering Techniques (#98) | 2019 | 11 |
| The State of the Marine Environment (#39) | 1990 | 10 |
| Guidelines for the Monitoring and Assessment of Plastic Litter in the Ocean (#99) | 2019 | 10 |
| Estimates of Oil Entering the Marine Environment from Sea-based Activities (#75) | 2007 | 9 |
| Proceedings of the GESAMP Workshop on Microplastic particles (#82) | 2010 | 9 |
| GESAMP Hazard Evaluation Procedure for Chemicals carried by Ships, 2019 (#102) | 2020 | 8 |
| Protecting the Oceans from Land-based Activities (#71) | 2001 | 7 |
| Impact of Oil and Related Chemicals on the Marine Environment (#50) | 1993 | 6 |
| Global Pollution Trends: Coastal Ecosystem Assessment for the Past Century (#106) | 2020 | 5 |
| Sea-based sources of marine litter (#108) | 2021 | 5 |

# Discussion and conclusion

This study shows that since Cordes (2003) and MacDonald et al. (2004), there has been a steady increase in the number of citations to GESAMP publications in scholarly literature and a sharp increase since 2016. This trend is noticeable in news and policy documents, with mentions increasing steadily from 2000 onwards. These trends may be due to increased public attention to climate change and ocean pollution. For instance, the UN's First World Ocean Assessment, released in 2017, exposed the degraded state of the oceans (UNESCO, 2017) and catalyzed national action. Canada, for example, launched a \$1.5 billion Oceans Protection Plan (OPP), the largest federal government investment to protect oceans (DFO Maritimes Region OPP Atlantic Hub, 2020). Such efforts around the globe may have spurred research drawing on GESAMP publications. As 2021 marked the beginning of the UN Decade of Ocean Science for Sustainable Development, GESAMP reports will likely continue to be needed and used, as evidenced by a rise in news mentions in 2022.  

Scientific attention, defined as the number of citations, can be observed mainly in fields and journals dealing with environmental and marine pollution, such as Marine Pollution Bulletin, Science of the Total Environment, or Environmental Pollution, as they tend to cite GESAMP the most. However, Ocean & Coastal Management and Marine Policy are also among the top citing journals, showing environmental management research is another field interested in GESAMP’s work. Moreover, mentions in policy documents indicate the relevance of GESAMP for governance and official bodies. Though it’s mostly UN organizations that draw from GESAMP, the expert group is also referenced in documents produced by the Canadian and United Kingdom governments and by organizations such as the International Union for Conservation of Nature.

The prevalence of attention to Sources, fate, and effects of microplastics in the marine environment (Parts 1 and 2) reifies the importance of plastic pollution, especially microplastics, particularly in recent years. As a result of the degradation of plastic components in ocean waters, microplastics pose several threats to marine life and human health through their ingestion and accumulation in the food chain. These reports were highly discussed and mobilized in news media when published. In this regard, GESAMP work has been foundational in estimating the size of the problem and building a better understanding of the issue. This also instantiates how scientific advisory bodies serve a key role in discovering and building knowledge on new public issues by mobilizing resources at a larger scale. Overall, pollution, especially plastic, oil, or chemicals, is central to GESAMP's most cited and mentioned work, thus highlighting its position as a key actor in tackling these issues. We also observe that GESAMP's most mentioned work in policy documents and news media was published in recent years, a stark comparison to citations. This is likely the result of two phenomena: 1) the comparatively quicker pace at which public attention may accumulate to alternative formats and 2) digital transformations that make relevant information more easily accessible, especially to policymakers. 

These results reveal the global use of GESAMP publications, their relevance to specific locales, and their utility to organizations with diverse purposes not solely limited to environmental or marine protection. Nevertheless, GESAMP publications remain most cited by its sponsoring organizations, such as UNEP, the FAO, and the WMO. Adie (2023) notes that concerning policy, governments tend to mostly cite locally. In this way, international bodies such as the UN, citing GESAMP literature, reveal how its findings may apply to work and policy with a global focus and less to regionalized policy. GESAMP reports are nevertheless regularly mentioned by national organizations, as evidenced by governmental and NGO documents from Australia, Canada, New Zealand, and Finland, among others. 

This analysis of literature citing GESAMP publications used references in scholarly articles from the Web of Science, policy documents from Overton, and news mentions from Factiva, Eurêka, ProQuest News and Newspapers, NexisUni, and Research Library. It finds that most citations are in scientific articles (4,713 citations from 4,082 distinct articles), followed by news sources (708 news mentions from 329 different news sources) and policy documents (742 policy citations from 551 publications published by 103 organizations linking to 118 GESAMP publications). It observes continuous growth of engagement with GESAMP publications over time, both in citations and in mentions of GESAMP literature in news media. 

This study’s approach possesses several limitations. A search for GESAMP publications was conducted across databases by searching for "gesamp" and its full name. Reports were not searched for at an individual level, potentially limiting the comprehensiveness of retrieved results from databases. As exhaustive as our data sources may be, this report may present an undervaluation of GESAMP literature; Overton and Web of Science do not index full coverage of GESAMP publications. Further, availability bias in Overton and policy documents online may skew our dataset. Some countries have fewer policies available online than others or use references in the same ways, potentially excluding mentions of GESAMP. Regarding news sources, databases do not typically distinguish between media, newswire, or news-feeding services. Future work will be needed to disambiguate the provenance and different layers of news services in the data.

# Data Statement

The code is available on GitHb (https://github.com/toupinr/gesamp), and aggregated data will be made available upon acceptance. However, full data obtained from Web of Science, Overton and news indexing platforms require access to these services. Interested readers can contact Clarivate (Web of Science: https://clarivate.com/academia-government/scientific-and-academic-research/research-discovery-and-referencing/web-of-science/) and Overton (https://www.overton.io/) for further access.

# Acknowledgements

The authors would like to thank Peter Wells and Bertrum MacDonald, whose expertise has been invaluable to the fulfillment of this research project on GESAMP’s work.

# CRediT Authorship Contributions

**Rémi Toupin**: Conceptualization, Methodology, Investigation, Formal Analysis, Writing – Original Draft, Writing - Review & Editing, Supervision, Funding Acquisition, Visualization

**Madelaine Hare**: Conceptualization, Methodology, Investigation, Formal Analysis, Writing – Original Draft, Writing - Review & Editing, Funding Acquisition

**Kellie Dalton**: Methodology, Investigation, Formal Analysis, Writing – Original Draft

**Geoff Krause**: Methodology, Investigation, Formal Analysis, Data Curation, Writing – Original Draft, Writing - Review & Editing

**Valeriia Moroz**: Investigation, Formal Analysis, Writing – Original Draft

**Philippe Mongeon**: Conceptualization, Methodology, Software, Investigation, Resources, Formal Analysis, Data Curation, Writing – Original Draft, Writing - Review & Editing, Supervision, Project Administration, Funding Acquisition

# Funding Sources

This project is funded by a Social Sciences and Humanities Research Council of Canada (SSHRC) Partnership Engage Grant (#892-2023-0067) with the Joint Group of Experts on the Scientific Aspects of Marine Environmental Protection (GESAMP). Resources provided by GESAMP are gratefully acknowledged. RT is also funded by a Fonds de recherche du Québec—Culture et Société postdoctoral fellowship (#313092; <https://frq.gouv.qc.ca>).

# References
