project:
  type: website

website:
  title: "quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - team.qmd
      - publications.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

